networks:
  transparenc:
    driver: bridge

volumes:
  pgdata:
  client_tokens:
  device_oauth_config:


services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - transparenc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./APIServer
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./APIServer:/app
      - device_oauth_config:/root/.config/intercom-api
      - client_tokens:/root/.config/intercomclient
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - transparenc
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://0.0.0.0:8000/api/v1/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    command: sh /app/start.sh

  device_autoapprove:
    build:
      context: ./APIServer
      dockerfile: Dockerfile.dev
    volumes:
      - ./APIServer:/app
    env_file:
      - .env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - transparenc
    profiles:
      - client
    command: uv run python manage.py auto_approve_devices --user ${DJANGO_LOCAL_DEV_USER}

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - transparenc

  clientpython:
    build:
      context: ./ClientPython
      dockerfile: Dockerfile.dev
    volumes:
      - ./ClientPython:/app
      - device_oauth_config:/root/.config/intercom-api
      - client_tokens:/root/.config/intercomclient
    env_file:
      - .env
    environment:
      - HTTP_API_BASE_URL=http://backend:8000
      - WEBSOCKET_API_BASE_URL=ws://backend:8000
      - TOKEN_FILE_PATH=/root/.config/intercomclient/tokens.json
    depends_on:
      device_autoapprove:
        condition: service_started
    networks:
      - transparenc
    profiles:
      - client
    command: uv run python main.py
