networks:
  transparenc:
    driver: bridge

volumes:
  pgdata:


services:
  postgres_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"         
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - transparenc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s

  backend:
    build:
      context: ./APIServer
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./APIServer:/app         
    environment:
      - DEBUG=1
      - POSTGRES_HOST=postgres_db
    env_file:
      - .env
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - transparenc
    healthcheck:
      test: ["CMD-SHELL", "wget", "http://localhost:8000/health/"]
      interval: 5s
      timeout: 5s
      retries: 10
    command: uv run python manage.py runserver 0.0.0.0:8000

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./Frontend:/app
      - /app/node_modules     # avoid overwriting container's node_modules
    # depends_on:
    #   backend:
    #     condition: service_healthy      
    env_file:
      - .env
    networks:
      - transparenc

  # client1:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./client:/app
  #   environment:
  #     - API_BASE_URL=http://backend:8000
  #     - CLIENT_ID=1
  #   depends_on:
  #     - backend
  #   networks:
  # -transparenc
  #   # If the client is a one‑shot script, override command: ["python", "client.py"]
  #   # If it's a long‑running service, keep as is.
